### ISSUE TITLE
Update JavaScript dependencies used by logs and reports internally

### ISSUE THREAD

**Issue by Aga303** [robotframework/robotframework#2419]
The js-dependencies in the generated log files are rather old.
e.g. jquery: 1.8.3 vs. 3.1.0

Uplifting jquery might at least partially mitigate the Robot Framework Jenkins Plugin CSP-problems:
https://issues.jenkins-ci.org/browse/JENKINS-32118

Might mitigate some future issues with browser compatibility too. :-)

**Comment by pekkaklarck** [comment]
First of all, sorry for ignoring this issue for so long. It was buried under a pile of other issues during summer time when I didn't have much time to follow this tracker.

The Jenkins problem you referred is related security changes in Jenkins itself and I'm not aware of any bugs in logs/reports related to us using old JS dependencies like jQuery. That said, updating the dependencies is a good idea, because the newer versions may have better performance and fixes for bugs we haven't even encountered.

Changing dependencies requires testing that everything still works afterwards. I'm mostly worried how the jQuery template plugin works with the latest jQuery versions because that plugin isn't anymore maintained. Unless bugs caused by the current dependencies and fixed by newer versions are reported, it is better to wait until the next major version.

**Comment by rubygeek** [comment]
I downloaded a copy of Robot Framework and updated the JQ version to the latest 3.3.1. The tests ran the and reports still worked locally when viewed in a browser. I installed a new instance of Jenkins and create a Jenkins job running my modified copy of RF against the same test. Upon viewing the report in Jenkins, the problem still remains. 

It could be that updating the other JS libraries will fix the CSP issue. Or it could be somewhere else entirely. 🤔

**Comment by rubygeek** [comment]
default jenkins permissions do NOT allow any jenkins:

https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy

**Comment by pekkaklarck** [comment]
Thanks @rubygeek for testing. Our logs and reports are dynamically created using Javascript, so it seems it's impossible to get them working with Jenkins default CSP. I would say it's still a good idea to upgrade jQuery and other dependencies in RF 3.1.

**Comment by pekkaklarck** [comment]
Dependencies we have in logs/reports, their versions, and possible changes we've done to them are listed in version control:
https://github.com/robotframework/robotframework/blob/master/src/robot/htmldata/lib/versions.txt

Listing them here as well as a reminder to go them all through:
- jquery
- jquery.tmpl
- jsxcompressor
- jquery.tablesorter
- jquery.highlight

**Comment by pekkaklarck** [comment]
We are going to upgrade jQuery to 3.3.1 This means IE 8 is not anymore supported:
https://jquery.com/upgrade-guide/3.0/#browser-support

**Comment by pekkaklarck** [comment]
Updated jquery, jsxcompressor and jquery.tablesorter. It seems jquery.tmpl and jquery.highlight are both deprecated/dead and thus don't need to be updated.

Logs/reports seem to work fine after the updated but I haven't done extensive testing with different browsers. Report if you encounter issues!
